version: '3.8'
services:
  storyteller-bot:
    build: .
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      # Монтируем yc config с хоста внутрь контейнера
      - ~/.config/yandex-cloud:/root/.config/yandex-cloud:ro
